### ISSUE TITLE
Cell editors float above the locked regions when scrolled

### ISSUE THREAD

**Issue by panderson1973** [keckeroo/css-locked-grid#11]
When cell editing is enabled and you are editing a cell value the zIndex of the cell editor is set to '10 !important'
This value is the same zIndex as the locked region and so when scrolled into the locked region the cell editor overlays the locked region.

Either the cell editors zIndex needs to be dropped, or we increase the zIndex of the locked regions.
I think the fix here is to have the locked regions use a zIndex higher than 10, this avoids conflicts within the existing framework.

**Comment by keckeroo** [comment]
Resolved in commit c3ddeaaa513eef58733877653dd1c9e05f1b3e0e
