### ISSUE TITLE
Selection model extender square is also visible over the locked regions

### ISSUE THREAD

**Issue by panderson1973** [keckeroo/css-locked-grid#12]
This is a duplicate issue of the cell editor, only this time it relates to the selection extender.
The selection extender square has a zIndex of 12, and thus is floating above the locked region which has a zIndex of 10.

The fix should probably be to increase the zIndex of the locked regions.

**Comment by keckeroo** [comment]
Fixed in 25277f49ddc391f47701dba8442586768fdefe6d

Issue was do to using absolute position values vs relative to grid body position values.

Also updated plugin name to 'csslockedgrid'
Also updated SASS file to encapsulate all styling for this package 

@panderson1973
