### ISSUE TITLE
Exception generated within Location.js (missing brackets)

### ISSUE THREAD

**Issue by panderson1973** [keckeroo/css-locked-grid#16]
An exception can be generated on line 71 of Location.js
The code:
`var count = isVirtualStore ? store.getCount() : store.getData.count();`
should read:
`var count = isVirtualStore ? store.getCount() : store.getData().count();`

**Comment by keckeroo** [comment]
Fixed issue with commit 2bd79de531f40151ede00af28523d9bb5bee3d93

Both regular and virtual stores have getCount() which return the total number of records currently available for displaying in view. This fixed navigation for virtual stores when attempting to navigate past pages in cache.
